In [18]:
import numpy as np
import pandas as pd

In [19]:
pip install datasets

Requirement already satisfied: datasets in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (4.5.0)
Requirement already satisfied: filelock in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (3.24.3)
Requirement already satisfied: numpy>=1.17 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (2.2.2)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (2.32.3)
Requirement already satisfied: httpx<1.0.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (1.4.1)
Requirement already satisfied: packaging in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.11.14)
Requirement already satisfied: anyio in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (4.9.0)
Requirement already satisfied: certifi in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (1.0.7)
Requirement already satisfied: idna in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: shellingham in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: colorama in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.18.3)
Requirement already satisfied: six>=1.5 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: typer>=0.24.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: click>=8.2.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
from datasets import load_dataset

In [25]:
emotions = load_dataset("go_emotions")

test = emotions["test"].to_pandas()
train = emotions["train"].to_pandas()
validation = emotions["validation"].to_pandas()

In [26]:
import pandas as pd
combined_df = pd.concat([train, validation, test], ignore_index=True)

In [27]:
combined_df.to_csv("dataset.csv", index=False)

In [ ]:
data = pd.read_csv("C:/Users/Atharva Nair/kavaach/ml-model/data/goemotions.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54263 entries, 0 to 54262
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    54263 non-null  object
 1   labels  54263 non-null  object
 2   id      54263 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB

In [36]:
MELD = load_dataset("TwinkStart/MELD")

README.md: 0.00B [00:00, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/17 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/17 [00:00<?, ?files/s]

data/test-00000-of-00017.parquet:   0%|          | 0.00/84.0M [00:00<?, ?B/s]

data/test-00001-of-00017.parquet:   0%|          | 0.00/89.2M [00:00<?, ?B/s]

data/test-00002-of-00017.parquet:   0%|          | 0.00/138M [00:00<?, ?B/s]

data/test-00003-of-00017.parquet:   0%|          | 0.00/90.3M [00:00<?, ?B/s]

data/test-00004-of-00017.parquet:   0%|          | 0.00/82.4M [00:00<?, ?B/s]

data/test-00005-of-00017.parquet:   0%|          | 0.00/82.1M [00:00<?, ?B/s]

data/test-00006-of-00017.parquet:   0%|          | 0.00/97.9M [00:00<?, ?B/s]

data/test-00007-of-00017.parquet:   0%|          | 0.00/80.5M [00:00<?, ?B/s]

data/test-00008-of-00017.parquet:   0%|          | 0.00/74.0M [00:00<?, ?B/s]

data/test-00009-of-00017.parquet:   0%|          | 0.00/88.7M [00:00<?, ?B/s]

data/test-00010-of-00017.parquet:   0%|          | 0.00/72.5M [00:00<?, ?B/s]

data/test-00011-of-00017.parquet:   0%|          | 0.00/85.6M [00:00<?, ?B/s]

data/test-00012-of-00017.parquet:   0%|          | 0.00/85.6M [00:00<?, ?B/s]

data/test-00013-of-00017.parquet:   0%|          | 0.00/128M [00:00<?, ?B/s]

data/test-00014-of-00017.parquet:   0%|          | 0.00/88.5M [00:00<?, ?B/s]

data/test-00015-of-00017.parquet:   0%|          | 0.00/78.3M [00:00<?, ?B/s]

data/test-00016-of-00017.parquet:   0%|          | 0.00/85.6M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/2610 [00:00<?, ? examples/s]

In [46]:
print(MELD)

DatasetDict({
    test: Dataset({
        features: ['Sr No.', 'Utterance', 'Speaker', 'Emotion', 'Sentiment', 'Dialogue_ID', 'Utterance_ID', 'Season', 'Episode', 'StartTime', 'EndTime', 'video_path', 'WavPath', 'audio'],
        num_rows: 2610
    })
})

In [52]:
dataset_meld1 = MELD["test"]
dataset_meld = dataset_meld1.to_pandas()

In [53]:
dataset_meld.head()

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime,video_path,WavPath,audio
0,1,Why do all youre coffee mugs have numbers on ...,Mark,surprise,positive,0,0,3,19,"00:14:38,127","00:14:40,378",MELD.Raw/output_repeated_splits_test/dia0_utt0...,MELD.Raw/output_repeated_splits_test/dia0_utt0...,{'bytes': b'RIFFz\x16\x06\x00WAVEfmt \x10\x00\...
1,2,Oh. Thats so Monica can keep track. That way ...,Rachel,anger,negative,0,1,3,19,"00:14:40,629","00:14:47,385",MELD.Raw/output_repeated_splits_test/dia0_utt1...,MELD.Raw/output_repeated_splits_test/dia0_utt1...,{'bytes': b'RIFF*4\x12\x00WAVEfmt \x10\x00\x00...
2,3,Y'know what?,Rachel,neutral,neutral,0,2,3,19,"00:14:56,353","00:14:57,520",MELD.Raw/output_repeated_splits_test/dia0_utt2...,MELD.Raw/output_repeated_splits_test/dia0_utt2...,{'bytes': b'RIFF\xc6(\x03\x00WAVEfmt \x10\x00\...
3,19,"Come on, Lydia, you can do it.",Joey,neutral,neutral,1,0,1,23,"0:10:44,769","0:10:46,146",MELD.Raw/output_repeated_splits_test/dia1_utt0...,MELD.Raw/output_repeated_splits_test/dia1_utt0...,{'bytes': b'RIFF\x16f\x05\x00WAVEfmt \x10\x00\...
4,20,Push!,Joey,joy,positive,1,1,1,23,"0:10:46,146","0:10:46,833",MELD.Raw/output_repeated_splits_test/dia1_utt1...,MELD.Raw/output_repeated_splits_test/dia1_utt1...,{'bytes': b'RIFF\xaa\xd6\x01\x00WAVEfmt \x10\x...

In [57]:
dataset_meld = dataset_meld[["Sr No.", "Utterance", "Emotion", "Sentiment"]]
dataset_meld

,Sr No.,Utterance,Emotion,Sentiment
0,1,Why do all youre coffee mugs have numbers on ...,surprise,positive
1,2,Oh. Thats so Monica can keep track. That way ...,anger,negative
2,3,Y'know what?,neutral,neutral
3,19,"Come on, Lydia, you can do it.",neutral,neutral
4,20,Push!,joy,positive
...,...,...,...,...
2605,2760,"Yeah, I mean, come on Ross, no one will even n...",neutral,neutral
2606,2761,They’re not listening too me?,surprise,negative
2607,2762,Of course they’re listening to you! Everybody ...,neutral,neutral
2608,2763,Monica you really think I should try this phas...,neutral,neutral
2609,2764,I think you look fine.,neutral,neutral

In [58]:
dataset_meld.to_csv("meld_dataset.csv", index=False)

In [66]:
empathetic = load_dataset("bdotloh/empathetic-dialogues-contexts")

README.md:   0%|          | 0.00/540 [00:00<?, ?B/s]

train.csv: 0.00B [00:00, ?B/s]

valid.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/19209 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2756 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2542 [00:00<?, ? examples/s]

In [69]:
train_empathetic = empathetic["train"].to_pandas()
test_empathetic = empathetic["test"].to_pandas()
val_empathetic = empathetic["validation"].to_pandas()

In [ ]:
combined_emphatetic = pd.concat([train_empathetic, test_empathetic, val_empathetic], ignore_index=True)
combined_emphatetic.to_csv("empathetic_dialogues.csv", index=False)

In [80]:
dataset = pd.read_csv("C:/Users/Atharva Nair/kavaach/ml-model/data/combined_final_dataset.csv")
dataset.head()

,Sr No.,text,labels,filename
0,1,Why do all youre coffee mugs have numbers on ...,"['Urgency', 'Anxiety']",emotion_dataset.csv
1,2,Oh. Thats so Monica can keep track. That way ...,"['Aggression', 'Coercion']",emotion_dataset.csv
2,3,Y'know what?,['Calm'],emotion_dataset.csv
3,4,"Come on, Lydia, you can do it.",['Calm'],emotion_dataset.csv
4,5,Push!,['Calm'],emotion_dataset.csv